name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Mise
        run: curl https://mise.run | sh

      - name: Install Tools
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ~/.local/bin/mise install
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - run: mise x -- gleam deps download
      - run: mise x -- gleam test
      - run: mise x -- gleam format --check src test
